sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - secure: "pG6PUcPrIl/IRHzrIvxrojIWzCJfIRVwTCFKQoQSK+CqhNMAuK6TYsuhujxDl558DZOyXowCLsvI8CGeph9gxlmKWOJUPoWjAE/28wITNXh634eDnHS5x1ahjAvxsbyT30tKxyaFVYYgEzgn0bCyKZxszNnHHaXr9Gp+oCmkk8DmVFkFHv+oyFClTDFZwoNNpc+gUUhEQVnBkkoP6E5ASMjatv5po/6AKIaxNBbrq3XopwnT6T3qBkGNPgoxjzquHPAXrgSCNhjmtC3jcy+yGbWNrMB17xo8QaGUTyBT4hEZ3Lj4km9No9RZSNp7MO9EPaZepHac/lNe/NGHHgYTgmqTb38kOCP2Bm1YrdnE/S9igKZ8HzsYoqNGKUGdtg7kvFgNuUv5RQaJtEVDlV282ZbEnsyk8u4opzlWcNzYNwzccVt9cIfPvw1pT8JYuOqy4qO4/sDxocbCTYuDb882v60dOcajOeu42Ro01EieuEcsy4fQiifN6Pc+GaYYHpPLXexp6PFNBBH6V4MeIBrimm7m0Khkdr0gTueRy/b+WqNY9ByoxH9jt2Quw2hq5MPdG3q6i8X4EZxQhJyZdEa0O3uEjXmAoTe2zdGMcZ7OWo1UsjcwJNb1HD/IzBzfiFu4oTgoPE3tjYn46b55OvOZz3w1v6UvzOggy66TLHJ08F8="
    - secure: "nUYbXIJU/4CvC5FZPK+qofLNVbzyBwEPjfTmeaKcp7EwnvK9lCWAIz5Fl2Hjgguz33AXnWwBydN9uEkqih0l8VcP3EVxseh7sCofzQ9B4t3NOMPWqaRNXallkx6BYlOEWl9DPJ1IQtEDHRweTAy750wxi7VesOTyXgjzSzIA6yoqjE+iJvZi0mYS7Z2VpbxcrHqFPdWv4zTNMisX+BNEOzClvpFtwa4fi5TxeOebQc9e5k4qW9oJ3Yqbw0/cwyliJwSKo5+IKa3Fsv+iuI8D7cCXJuLJdZza0bMhP0dPzTpfjc+/BdRF/VxJ5fM1jsztuZCSsHSEjNIjAtU97nCwKm4zaM8mgnfJB/N4LMaRBQJ6a3mTAYu61PpH/rVVcvC8opbM5VOzv8LISxG/1VdOHoFQF2wpBqRzs2Lb16QRW7bQ9wmu60enZHaqWV4+T4QQ8n0VyC9MvbPJf6QVAZQa2rE9hJJ9GJn93M/hv5LYfyrQDnfGAZ1j4AuSQJ+j/P64XPXVhtN16lNXiSNoRv0cUQFD3HXc1HqFGk10yzT+P22jHKxa5fnlVzwFjJ67zRXdde9fRA8IIOjTfvhauGirwPAUkOMlc9I0TtJW736ELTQexpAcIKBXWM36lZPMF05nxz4mv878/9A9pF4aDCNqohfLX6PuQbWa094vv2R2KFs="

before_install:
  - sudo /etc/init.d/postgresql stop
  - docker build -t blackducksoftware/bdio-tinkerpop-db bdio-tinkerpop-db/
  - docker run -d -p 5432:5432 blackducksoftware/bdio-tinkerpop-db
install: ./gradlew -I gradle/travis.gradle assemble
script: ./gradlew -I gradle/travis.gradle check
after_success: ./gradlew -I gradle/travis.gradle publish

deploy:
  provider: releases
  api_key:
    secure: "htUa59FiJ5QpeOmGHS/kfYNehBMlB8kx03T494WOENjiGIxSd+TM/X9WM4Tm3N74y20qalEofhRagMzutQ7vYZg6Bj1l1InP8OzKIokRk7hZJAwAhe+05Df/OrOGGZuyyccVB+NhdysAmU8lPDYoZX1uTexSb0/+TeeLubN0UzQ3QyjQ2OKaH5vU0pBAvH+4zpenH6HrX86BBdQYfz4ewug+pUKWBMGHFYjjAv0Vridr1HVR6qHumXm0I4wRlxe1bbgXe2AYevjvvBmM2eGT1TSAecFxDwCjQf5FTju1rbnHJVfZOHnapqZqwNiBp3zB8NRJyppanxBLzs+1LUiwtZt2h4JRCjz17QhSn0vhAF4KJrX/GZ7lzRYdH+TIl52nXQLS7wQv7DuOcJvQZtXAd3SXK0HjLE6mm3bbEF/5b5LyererOe15+vmLiwItSCaQ94E/hW1jZ3jQaMRzvV87UpmJjvhwTpA1mVsybN0ZyryuxHtEnKCfw/SBVJUoF+5Uop4vlrfYqSzU5dgXwlP16sRFzT0iZVvPpRmf9sjBMMs+OOal5X9vl+Gu9fSHh6SBP/uolYqcV5W3yvtdab5rdoHBGrLXao5yytZ0dYtuj01QpmpGxBX5wOeB6kKzM5HuoD+NuGnDkCYVvwT+NGJwFxctVxOYWSyQXboSEHaINyg="
  file:
    - "bdio-tool/build/distributions/bdio-$TRAVIS_TAG.zip"
    - "bdio-tool/build/distributions/bdio-$TRAVIS_TAG.tar"
  skip_cleanup: true
  on:
    tags: true
