language: java

jdk:
  - oraclejdk7

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - secure: "BQhD1P7AobIxF8i3h+EMv3iWXz+y2iqnsEncnlP+CAyMCIp4rvUEbTH9nen9xxYt1wiF4HC+nI83Y3+vV5HUMeMiEOrOnLct9LVnbT+34Izk9QOSasXD5lzkdTpla1wgRlciiiZYFNNQOscCTGyowBQU+WXOI2x+3NuFypD3fDMrWPzBrdSqdZ81enQH35nMapWDZK7mCOux7KPKkVRafImvnGn8YZMSjWyq2TWPUw9jsgl7WRAgIzxWZDVHLgiDEBCnYs+dwb6VGJjiDz7HkEvb/o3Qm9Pae7CuSuzUe97e9bwSSotNmkmCMmhYN1sVpjrJUz7wUT9vlcJC5n3ZMWe7e2L3sWUW5vSFdJq5yyaFkQl8N+/MGVknoNa0NyMs6kiVQNvrkkklaPg6YKLU6svp4ivmbRL0R231Yl/ko7y08j1tvUgSz5WpxoVli6qDNeGXCL6jcjZRIsO28GNO9B6thz88NFNlzBkVEJ9ds1rRjyF98e3er5CKspHOzHmRxls1zqTYsK71Gi5UH3DM6MvGlI9Vnllebb/owHnY3SWclsOS02DnlJpeq+iPFcvHteSvUC/BtoPUG1ItevTmsa5MCQcwygMgmM/k75YHzU/SVwLpbGJXKWzqK46tVByFAGnATnOrqoBUQt4qaeJ+BwpVdm/m1Uzdm5C8dnDQ34M="
    - secure: "XvJq44c+Ku9W2U5PE23TIJzXmhZjmzVkG8FpSTrPeQirTQBwmqKTGS6cp8S9YQk2vIEnGF8+HR7ku99nzgjhbkG9N+AtUExaHKlCHBkwo+hsXiORZPXz0/lOPjtINqGlagAxA8HmekAs8Ks15iBKn5+hjqL1nhpZGHo3or8BjVR3g5FctKpq60TUNK7XSPILiePIhhwUIbJtUqo5A+vBF5R0UfxsTF01SbW/XPqUCWi8BcYQRKTJoqSP1BXT9Bg5EurFVg8j6tRV/OaG2F7mEVNA8hn3j8UFIQqTtgiJ7fgrxiuwwXxxoZWpWfIWDG9SC9WDSN58mFJFTAmjnOVJiCPpqp7pHdenG43T/xEWPQx8tgTLtO/1MCztTrq+rLCbityNTpGp8OOs/Gem/os7a7iJRToL/k/KHRVc5ZVWyZSYtXF6w29h9QeKeQPznBy80jWezzPmx1KhoItLfQVO3AQ2OYpwzK3AsfB55pE/CvYrkLngnbnjHo8N/TKzMf7/pIy2PNMsFKvZ63bnQuO6z7ehBW3mQU2M3OxB5xM2bf4vSl/Knt4sDzXZFFh9t344HGRGLPdqUM3L//awXiI02ffsD+zx8b7TpWKRNZTTKSwRuZRi1bIVBM4adAFUtt4PHXl/3KCvjMqIXYHFrZty1qV/nZwQeaqpAmuIr2yCYbU="

after_success: ./gradlew -I gradle/travis.gradle publish
