language: java

jdk:
  - oraclejdk8

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - secure: "pG6PUcPrIl/IRHzrIvxrojIWzCJfIRVwTCFKQoQSK+CqhNMAuK6TYsuhujxDl558DZOyXowCLsvI8CGeph9gxlmKWOJUPoWjAE/28wITNXh634eDnHS5x1ahjAvxsbyT30tKxyaFVYYgEzgn0bCyKZxszNnHHaXr9Gp+oCmkk8DmVFkFHv+oyFClTDFZwoNNpc+gUUhEQVnBkkoP6E5ASMjatv5po/6AKIaxNBbrq3XopwnT6T3qBkGNPgoxjzquHPAXrgSCNhjmtC3jcy+yGbWNrMB17xo8QaGUTyBT4hEZ3Lj4km9No9RZSNp7MO9EPaZepHac/lNe/NGHHgYTgmqTb38kOCP2Bm1YrdnE/S9igKZ8HzsYoqNGKUGdtg7kvFgNuUv5RQaJtEVDlV282ZbEnsyk8u4opzlWcNzYNwzccVt9cIfPvw1pT8JYuOqy4qO4/sDxocbCTYuDb882v60dOcajOeu42Ro01EieuEcsy4fQiifN6Pc+GaYYHpPLXexp6PFNBBH6V4MeIBrimm7m0Khkdr0gTueRy/b+WqNY9ByoxH9jt2Quw2hq5MPdG3q6i8X4EZxQhJyZdEa0O3uEjXmAoTe2zdGMcZ7OWo1UsjcwJNb1HD/IzBzfiFu4oTgoPE3tjYn46b55OvOZz3w1v6UvzOggy66TLHJ08F8="
    - secure: "nUYbXIJU/4CvC5FZPK+qofLNVbzyBwEPjfTmeaKcp7EwnvK9lCWAIz5Fl2Hjgguz33AXnWwBydN9uEkqih0l8VcP3EVxseh7sCofzQ9B4t3NOMPWqaRNXallkx6BYlOEWl9DPJ1IQtEDHRweTAy750wxi7VesOTyXgjzSzIA6yoqjE+iJvZi0mYS7Z2VpbxcrHqFPdWv4zTNMisX+BNEOzClvpFtwa4fi5TxeOebQc9e5k4qW9oJ3Yqbw0/cwyliJwSKo5+IKa3Fsv+iuI8D7cCXJuLJdZza0bMhP0dPzTpfjc+/BdRF/VxJ5fM1jsztuZCSsHSEjNIjAtU97nCwKm4zaM8mgnfJB/N4LMaRBQJ6a3mTAYu61PpH/rVVcvC8opbM5VOzv8LISxG/1VdOHoFQF2wpBqRzs2Lb16QRW7bQ9wmu60enZHaqWV4+T4QQ8n0VyC9MvbPJf6QVAZQa2rE9hJJ9GJn93M/hv5LYfyrQDnfGAZ1j4AuSQJ+j/P64XPXVhtN16lNXiSNoRv0cUQFD3HXc1HqFGk10yzT+P22jHKxa5fnlVzwFjJ67zRXdde9fRA8IIOjTfvhauGirwPAUkOMlc9I0TtJW736ELTQexpAcIKBXWM36lZPMF05nxz4mv878/9A9pF4aDCNqohfLX6PuQbWa094vv2R2KFs="

install: ./gradlew -I gradle/travis.gradle assemble
script: ./gradlew -I gradle/travis.gradle check
after_success:
  - ./gradlew -I gradle/travis.gradle publish
  - curl https://copilot.blackducksoftware.com/scripts/init/gradle -o bds_init.gradle
  - ./gradlew --init-script bds_init.gradle buildBom -DbdsPluginVersion=5.0.2
  - bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./build/blackduck/*_bdio.jsonld
