#!/bin/bash
set -e
VERSION=$(awk -F= '$1=="version"{print $2}' gradle.properties)
read -p "Enter the release version (${VERSION%-SNAPSHOT}): " RELEASE_VERSION
read -p "Enter the post-release version (${VERSION}): " POST_RELEASE_VERSION
RELEASE_VERSION="${RELEASE_VERSION:=${VERSION%-SNAPSHOT}}"
POST_RELEASE_VERSION="${POST_RELEASE_VERSION:=${VERSION}}"
POST_RELEASE_VERSION="${POST_RELEASE_VERSION%-SNAPSHOT}-SNAPSHOT"

echo $RELEASE_VERSION
echo $POST_RELEASE_VERSION
